name: Update packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  update:
    if: github.repository == 'fufexan/nix-gaming'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 5G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}
          # created more than this number of seconds ago
          purge-created: 0
          # or, last accessed more than this number of seconds ago
          # relative to the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: 0
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never

      - uses: cachix/cachix-action@v15
        with:
          name: nix-gaming
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: |
          nix run nixpkgs#npins update
          pkgs/faf-client/update.sh
          pkgs/faf-client/update-src.sh
          pkgs/osu-lazer-bin/update.sh
          pkgs/osu-stable/update.sh
          pkgs/proton-osu-bin/update.sh
          pkgs/wine/update-wine-ge.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update packages"
          push_options: '--force'

  build:
    needs: update
    uses: ./.github/workflows/build.yml
    secrets: inherit
